spring:
  application:
    name: xlsxeditor
server:
  port: 8080
app:
  prod:
    datasource:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: "jdbc:postgresql://10.10.10.10:5444/ccs_core"
      username: "user"
      password: "Ccs"
  stage:
    datasource:
      driver-class-name: org.postgresql.Driver
      jdbcUrl: "jdbc:postgresql://10.10.10.10:5444/ccs_core"
      username: "ccs"
      password: "Ccs"
