spring:
  application:
    name: autochecker
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://10.107.19.21:5444/ccs_core"
    username: "ccs_core_user"
    password: "Ccspdb2019!"
#    url: "jdbc:postgresql://45.76.32.22:5432/postgres"
#    username: "postgres"
#    password: "Moscow2020!"
server:
  port: 8081
connection:
  system_configs[0]:
    port: 22
    timeOut: 60000
    user: "root"
    password: "sochi2014!"
    connectionIp: "45.76.32.22"
conf:
  output:
    dir: "C:/NATI/projects/autocheck/src/main/resources/"
#    dir: "/home/hkmc/check"
  schedule:
    cron: "0 0 0 * * *"
    zone: "Europe/Moscow"

