spring:
  application:
    name: xlsxeditor
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://10.107.19.21:5444/ccs_core"
    username: "ccs_core_user"
    password: "Ccspdb2019!"
server:
  port: 8081

